### ISSUE TITLE
No stable download

### ISSUE THREAD

**Issue by Morples** [developer-lfierrro743/Project-EaglercraftY-1.9-version-Indev#1]

**Comment by lfierro743** [comment]
(okay thank you for Pointing  that )
There is No stable Files yet and No HTML file and actually no demo 
(this is Expemential build)
(I will implement it with a working Url and Html Links)

**Comment by professorparabellum** [comment]
sir you are not being truthful. 1.9 is not possible, please do not be untruthful with us

**Comment by ggsdfff** [comment]
hey, my singleplayer & muliplayer are crashed for me. Is their a way anybody can help me?? im using 1.52

**Comment by SnesLover22** [comment]
> hey, my singleplayer & muliplayer are crashed for me. Is their a way anybody can help me?? im using 1.52

this isn't the guy who made eaglercraft don't talk to him!! lax1dude made it, and he just got DMCA'd by Mojang so he can't help anymore. Also if you are using an older 1.5.2 version of eagler then it does crash. Sorry, just upgrade it. my site has the latest version if you want it: sneslover22.github.io/Mathews-Collection

**Comment by SnesLover22** [comment]
around 2022, the end of 2022. maybe december.

**Comment by SnesLover22** [comment]
maybe it was beginning of 2022... idk its been a while.

**Comment by FailedCoder23** [comment]
This probably is never getting added.
