### ISSUE TITLE
photoshopped picture

### ISSUE THREAD

**Issue by creativename420** [developer-lfierrro743/Project-EaglercraftY-1.9-version-Indev#6]
It looks very real and not photoshopped at all i'm sure that is the real test build!

**Comment by IceeFoox** [comment]
It seems like it is possible for 1.9.4

**Comment by skybase-alpha** [comment]
You never know.

**Comment by IceeFoox** [comment]
Ik, Just said that its possible since 1.5.2 and 1.8.8 were possible

**Comment by professorparabellum** [comment]
this is completely fake and this kid is a fat liar who doesnt know what he is doing
