### ISSUE TITLE
question

### ISSUE THREAD

**Issue by poodeveloper** [developer-lfierrro743/Project-EaglercraftY-1.9-version-Indev#8]
srry abt this correct me if i am wrong but is it possible to download it now and if so can you tell me how or do I have to deploy it on the something like netify...

**Comment by lfierro743** [comment]
Uh It not yet Ready 
For downloading yet

**Comment by poodeveloper** [comment]
k thx prob a stupid question

**Comment by lfierro743** [comment]
Are you a good Developer for Building a Code
like java,Html ?
I going need More Developers to Make EaglercraftY possible

**Comment by poodeveloper** [comment]
not at all lol srry :( i can't even do HTML srry

**Comment by lfierro743** [comment]
oh
